#! /bin/sh

bspc config border_width        1
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#eeeeee"
bspc config active_border_color  "#f8f8f8"
bspc config normal_border_color  "#ffffff"
bspc config presel_border_color  "#b32e37"

bspc monitor -d I


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
